---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: shared-llm

resources:
  # presync
  # wave 0
  - namespace.yaml
  - accelerator-profile.yaml
  # wave 1
  - serving-runtime-vllm-granite-modelcar.yaml
  # wave 2
  - inference-service-granite-modelcar.yaml