apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kafka-broker # The name for your Kafka-backed broker
  namespace: rag-pipeline-workshop # CHANGEME: Your serverless application namespace
  annotations:
    eventing.knative.dev/broker.class: Kafka # Specifies to use the Kafka-backed broker implementation
spec:
  # Reference the ConfigMap created above for Kafka-specific settings
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config # Must match the name of the ConfigMap
    namespace: rag-pipeline-workshop # Must match the namespace of the ConfigMap
  # Optional: Define delivery specifications like Dead Letter Sink (DLS), retry policies
  # delivery:
  #   deadLetterSink:
  #     ref:
  #       apiVersion: serving.knative.dev/v1
  #       kind: Service
  #       name: your-dead-letter-service # You would need to create this service
  #       namespace: rag-pipeline-workshop
  #   retry: 5

