apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: knative-broker
data:
  # Knative Kafka broker configuration
  bootstrap.servers: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  default.topic.partitions: "10"
  default.topic.replication.factor: "1"

