apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: minio-kafka-event-source
  namespace: rag-pipeline-workshop
spec:
  bootstrapServers:
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topics:
    - "minio-bucket-notifications"
  consumerGroup: knative-minio-consumer
  initialOffset: earliest
  cloudEventOverrides:
    extensions:
      eventType: "${EventName}"  # This will use the EventName from MinIO's event
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
      namespace: rag-pipeline-workshop
