apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller
    eventing.knative.dev/lastModifier: system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"eventing.knative.dev/v1","kind":"Trigger","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"knative-broker"},"name":"minio-pdf-event-trigger","namespace":"rag-pipeline-workshop"},"spec":{"broker":"kafka-broker","filter":{"attributes":{"source":"urn:minio:s3:::webhook","type":"s3:ObjectCreated:Put"}},"subscriber":{"uri":"http://kfp-s3-trigger.rag-pipeline-workshop.svc.cluster.local"}}}
  creationTimestamp: "2025-06-01T06:22:20Z"
  finalizers:
  - kafka.triggers.eventing.knative.dev
  generation: 1
  labels:
    app.kubernetes.io/instance: knative-broker
    eventing.knative.dev/broker: kafka-broker
  name: minio-pdf-event-trigger
  namespace: rag-pipeline-workshop
  resourceVersion: "9191179"
  uid: a0f7b05e-8297-4aaa-aebf-fdc7fa420cdc
spec:
  broker: kafka-broker
  filter:
    attributes:
      source: urn:minio:s3:::webhook
      type: s3:ObjectCreated:Put
  subscriber:
    uri: http://kfp-s3-trigger.rag-pipeline-workshop.svc.cluster.local
status:
  annotations:
    group.id: knative-trigger-rag-pipeline-workshop-minio-pdf-event-trigger
  conditions:
  - lastTransitionTime: "2025-06-01T06:33:34Z"
    status: "True"
    type: BrokerReady
  - lastTransitionTime: "2025-06-01T06:22:20Z"
    status: "True"
    type: DeadLetterSinkResolved
  - lastTransitionTime: "2025-06-01T06:22:20Z"
    status: "True"
    type: DependencyReady
  - lastTransitionTime: "2025-06-01T06:22:20Z"
    reason: authentication-oidc feature disabled
    status: "True"
    type: OIDCIdentityCreated
  - lastTransitionTime: "2025-06-01T06:33:34Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-01T06:22:20Z"
    status: "True"
    type: SubscriberResolved
  - lastTransitionTime: "2025-06-01T06:22:20Z"
    status: "True"
    type: SubscriptionReady
  observedGeneration: 1
  subscriberUri: http://kfp-s3-trigger.rag-pipeline-workshop.svc.cluster.local
