apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: minio-event-bridge-run-  # Using timestamp for uniqueness
  namespace: hello-chris-ai
spec:
  pipelineRef:
    name: hello-chris-ai-pipeline
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: tekton-pvc-mock-api # Matches the PVC name
  params:
  - name: namespace
    value: "hello-chris-ai"
  - name: deployment-name
    value: "hello-chris-ai"
  - name: git-url
    value: "https://github.com/cnuland/hello-chris-rag-pipeline.git"
  - name: git-revision
    value: "main" # Or your specific branch/commit
  - name: IMAGE
    # IMPORTANT: Replace with your Quay.io image URL
    value: "quay.io/cnuland/hello-chris-rag-pipeline-converter:latest"
  - name: dockerfile-path
    value: "Dockerfile" # Path to your main Dockerfile from the root of the git repo
  - name: context-path
    value: "." # Build context from the root of the git repo
  - name: TLSVERIFY
    value: "false"
  - name: NO_PROXY
    value: "true"
  - name: working-dir
    value: "apps/minio-event-bridge"
  # serviceAccountName: pipeline # Optional: if your pipeline needs specific permissions