apiVersion: serving.knative.dev/v1 # Standard Knative Serving API
kind: Service
metadata:
  name: kfp-s3-trigger # Name of your Knative Service
  namespace: rag-pipeline-workshop # CHANGEME: Target OpenShift project
  annotations:
    # Standard Knative annotation for scaling to zero. Works in OpenShift Serverless.
    autoscaling.knative.dev/minScale: "0"
    # OpenShift specific annotations can be added here if needed for specific behaviors
    # or UI integrations, but are often not required for basic functionality.
    # Example: To influence the generated OpenShift Route:
    # serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        # How long to keep a pod after it scales to zero.
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "10m"
    spec:
      serviceAccountName: kfp-trigger-sa # SA for KFP interaction (defined in rbac.yaml)
      containers:
        - image: quay.io/cnuland/hello-chris-rag-pipeline-event:latest # CHANGEME
          # Or, if using OpenShift internal registry:
          # image: image-registry.openshift-image-registry.svc:5000/your-serverless-project/s3-kfp-trigger:latest
          ports:
            - containerPort: 8080 # Port your application listens on
          env:
            - name: KFP_ENDPOINT
              # CHANGEME: Correct Kubeflow Pipelines API endpoint URL
              # e.g., http://ds-pipeline-pipelines-definition.your-openshift-ai-project.svc.cluster.local:8888
              value: "http://ds-pipeline-your-osai-project.apps.your-cluster.com"
            - name: KFP_PIPELINE_NAME
              value: "Simple PDF Processing Pipeline" # Must match uploaded KFP pipeline name
            - name: KFP_EXPERIMENT_NAME
              value: "S3 Triggered PDF Runs"
          resources: # Define appropriate resources
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: / # Assuming your Flask app responds to / for health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20