apiVersion: eventing.knative.dev/v1 # Standard Knative Eventing API
kind: Trigger
metadata:
  name: s3-pdf-upload-trigger-to-kfp
  namespace: hello-chris-rag-pipeline # CHANGEME: Target OpenShift project
spec:
  broker: default # Must match the name of your Broker
  filter:
    attributes:
      # This 'type' should match the CloudEvent type produced by radiorabe/minio-cloudevents-service
      type: "io.minio.objectcreated.put"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service # This is a Knative Service, not a Kubernetes Service
      name: kfp-s3-trigger # Name of your Knative Service defined in knative-service.yaml
    # uri: / # Optional: if your service needs events at a specific path