apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: s3-pdf-upload-trigger-to-kfp # Or your chosen trigger name
  namespace: rag-pipeline-workshop # Your serverless application namespace
spec:
  broker: kafka-broker # Points to your Kafka-backed broker
  filter:
    attributes:
      type: "dev.knative.kafka.event" # Type from KafkaSource
      # Ensure KafkaSource name is correct if this filter is used
      source: "/kafkasource/rag-pipeline-workshop/minio-kafka-event-source" 
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kfp-s3-trigger
      namespace: rag-pipeline-workshop