apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kfp-s3-trigger-unified-vs # Using the name from your first combined attempt
  namespace: rag-pipeline-workshop
spec:
  hosts:
    # Host for external ingress (from kfp-s3-trigger-ingress and kfp-s3-trigger-unified-vs)
    - "kfp-s3-trigger-rag-pipeline-workshop.apps.cluster-6wqbq.6wqbq.sandbox842.opentlc.com"
    # Host for internal mesh traffic (from all three original VirtualServices)
    - "kfp-s3-trigger.rag-pipeline-workshop.svc.cluster.local"
  gateways:
    # Gateway for external ingress (from kfp-s3-trigger-ingress and kfp-s3-trigger-unified-vs)
    - knative-serving/knative-ingress-gateway 
    # Gateway for internal mesh traffic (from kfp-s3-trigger-mesh and kfp-s3-trigger-unified-vs)
    - mesh 
  http:
    - match:
        # This general match condition applies to requests for any of the hosts 
        # coming through any of the gateways, matching all paths.
        - uri:
            prefix: "/"
      route:
        - destination:
            host: kfp-s3-trigger.rag-pipeline-workshop.svc.cluster.local
            port:
              number: 80
      # Timeout and Retries from your kfp-s3-trigger-mesh VirtualService
      # These will now apply to traffic matched by this http route block.
      timeout: 60s
      retries:
        attempts: 3
        perTryTimeout: 20s