apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-mock-api # Changed name slightly to be more specific
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi