apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
    app.kubernetes.io/instance: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2023-06-19T19-52-50Z
        args:
        - server
        - /data
        - --address
        - :9000
        - --console-address
        - :9090
        env:
        - name: MINIO_API_SECURE
          value: "off"
        - name: MINIO_NOTIFY_WEBHOOK_ENABLE_RAG
          value: "on"
        - name: MINIO_NOTIFY_WEBHOOK_ENDPOINT_RAG
          value: "http://minio-event-bridge.rag-pipeline-workshop.svc.cluster.local:8080/webhook"
        - name: MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_RAG
          value: ""
        - name: MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_RAG
          value: "/tmp/webhooks"
        - name: MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_RAG
          value: "10000"
        - name: MINIO_NOTIFY_WEBHOOK_CLIENT_CERT_RAG
          value: ""
        - name: MINIO_NOTIFY_WEBHOOK_COMMENT_RAG
          value: "Event notifications for PDF uploads"
        - name: MINIO_SERVER_URL
          value: "http://minio-s3-minio.apps.cluster-6wqbq.6wqbq.sandbox842.opentlc.com"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://minio-console-minio.apps.cluster-6wqbq.6wqbq.sandbox842.opentlc.com"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_USER
              name: minio-root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MINIO_ROOT_PASSWORD
              name: minio-root-user
        ports:
        - containerPort: 9000
          name: api
          protocol: TCP
        - containerPort: 9090
          name: console
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        volumeMounts:
        - mountPath: /data
          name: minio
      volumes:
      - name: minio
        persistentVolumeClaim:
          claimName: minio
