apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: minio
spec:
  template:
    spec:
      containers:
      - name: mc
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command:
        - /bin/sh
        - -c
        - |
          microdnf install -y curl
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          export HOME=/tmp
          echo "Waiting for MinIO to be ready..."
          for i in $(seq 1 30); do
            if curl -s http://minio:9000/minio/health/live; then
              echo "MinIO is ready. Configuring webhook..."
              ./mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --insecure
              if ./mc event add myminio/pdf-inbox arn:minio:webhook::RAG:webhook --event put --suffix .pdf; then
                echo "Webhook configuration successful"
                exit 0
              fi
            fi
            echo "Attempt $i: MinIO not ready yet, waiting..."
            sleep 2
          done
          echo "Failed to configure MinIO after 30 attempts"
          exit 1
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-root-user
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-root-user
              key: MINIO_ROOT_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
