apiVersion: v1
kind: Service
metadata:
  name: minio-cloudevents-service
  namespace: rag-pipeline-workshop
  labels:
    app: minio-cloudevents-service
spec:
  type: ClusterIP
  selector:
    app: minio-cloudevents-service
  ports:
  - protocol: TCP
    port: 8080 # Port the service will listen on
    targetPort: 8080 # Port the container exposes