apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-mock-api # Changed name slightly to be more specific
  namespace: hello-chris-ai # Replace with your target OpenShift project/namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi