apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/services/knative

# Any environment-specific customizations can be added here using patches
# patchesStrategicMerge:
# - patch.yaml

