---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2023-06-19T19-52-50Z
        args:
        - server
        - /data
        - --console-address
        - :9090
        env:
        - name: MINIO_NOTIFY_KAFKA_ENABLE_MYMINIOKAFKA
          value: "on"
        - name: MINIO_NOTIFY_KAFKA_BROKERS_MYMINIOKAFKA
          value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: MINIO_NOTIFY_KAFKA_TOPIC_MYMINIOKAFKA
          value: "minio-bucket-notifications"
        - name: MINIO_NOTIFY_KAFKA_TLS_MYMINIOKAFKA
          value: "off"
        - name: MINIO_NOTIFY_KAFKA_TLS_SKIP_VERIFY_MYMINIOKAFKA
          value: "on"
        - name: MINIO_NOTIFY_KAFKA_SASL_MYMINIOKAFKA
          value: "off"
        - name: MINIO_NOTIFY_WEBHOOK_ENABLE_RAG
          value: "on"
        - name: MINIO_NOTIFY_WEBHOOK_ENDPOINT_RAG
          value: "http://minio-event-bridge.rag-pipeline-workshop.svc.cluster.local:8080/webhook"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-root-user
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-root-user
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000
          protocol: TCP
          name: api
        - containerPort: 9090
          protocol: TCP
          name: console
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: minio
      volumes:
      - persistentVolumeClaim:
          claimName: minio
        name: minio
