apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: minio-internal
  namespace: minio
spec:
  hosts:
  - "minio.minio.svc.cluster.local"
  - "*"  # Accept traffic for any host, routing will be controlled by gateway selection
  gateways:
  - mesh  # For in-cluster communication via service mesh
  http:
  - match:
    - port: 9000
    route:
    - destination:
        host: minio.minio.svc.cluster.local
        port:
          number: 9000
  - match:
    - port: 9090
    route:
    - destination:
        host: minio.minio.svc.cluster.local
        port:
          number: 9090

