apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml # This creates the 'minio' namespace
  - secret.yaml
  - sa.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - network-policies.yaml
  - setup-minio.yaml