apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-egress
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/instance: minio
spec:
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: rag-pipeline-workshop
        podSelector:
          matchLabels:
            app: minio-event-bridge
      ports:
        - port: 8080
          protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-dns
        podSelector:
          matchLabels:
            dns.operator.openshift.io/daemonset-dns: default
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
      - ipBlock:
          cidr: 172.30.0.10/32
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system
      ports:
        - port: 15012
          protocol: TCP
        - port: 15017
          protocol: TCP
        - port: 15010
          protocol: TCP
        - port: 15014
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 8188
          protocol: TCP
        - port: 15021
          protocol: TCP
        - port: 15090
          protocol: TCP
        - port: 15053
          protocol: TCP
        - port: 15053
          protocol: UDP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-to-minio
  namespace: minio
  labels:
    app.kubernetes.io/instance: minio
spec:
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
    - Ingress
  ingress:
    - {}
