---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-manage
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-secrets
  namespace: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
- kind: ServiceAccount
  name: minio-manage
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "4"