apiVersion: v1
kind: Secret
metadata:
  name: minio-root-user
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opqaue
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123