---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
    app.kubernetes.io/instance: minio
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: minio-tls
spec:
  ports:
  - name: api
    port: 9000
    targetPort: api
  - name: console
    port: 9090
    targetPort: 9090
  selector:
    app: minio
  sessionAffinity: None
  type: ClusterIP