# Kubernetes Job to automatically configure MinIO buckets and event notifications.
# This Job is designed to be run via an ArgoCD Sync hook.
apiVersion: batch/v1
kind: Job
metadata:
  # Using generateName ensures a unique Job is created on each sync, avoiding immutability errors.
  # The hyphen at the end is important for Kubernetes to append a random suffix.
  generateName: minio-setup-
  # The namespace will be applied by Kustomize/ArgoCD.
  # namespace: minio # This is set by the ArgoCD Application destination
  annotations:
    # ArgoCD Hook: This Job will run during the sync phase in its specified wave.
    argocd.argoproj.io/hook: Sync
    # ArgoCD Sync Wave: Assigns the Job to a later wave, ensuring dependent resources are created first.
    argocd.argoproj.io/sync-wave: "10"
    # ArgoCD Hook Policy: The Job and its Pods will be deleted after successful completion.
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  # Controls how many times the Job will retry if a Pod fails.
  backoffLimit: 2
  template:
    spec:
      # This Service Account must exist before this Job's wave is executed.
      serviceAccountName: minio-manage
      restartPolicy: Never
      containers:
      - name: minio-setup-container
        # Use the official MinIO Client (mc) image.
        image: minio/mc:latest
        # The command to execute. It's a shell script that performs all necessary setup steps.
        command:
          - "/bin/sh"
          - "-c"
          - |
            set -e
            echo "--- Starting MinIO Setup Job ---"
            
            # Use a writable directory for mc config to avoid permission errors on OpenShift
            MC_CONFIG_DIR="/tmp/.mc"
            
            # 1. Wait for the MinIO service to be available and set alias.
            echo "Waiting for MinIO service at ${MINIO_SERVICE_HOST}:${MINIO_SERVICE_PORT}..."
            until mc --config-dir ${MC_CONFIG_DIR} alias set temp_minio http://${MINIO_SERVICE_HOST}:${MINIO_SERVICE_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; do
              echo "MinIO service not ready yet, retrying in 10 seconds..."
              sleep 10
            done
            echo "MinIO service is ready. Alias 'temp_minio' configured."
            
            # 2. Create the target bucket for PDF uploads if it doesn't exist.
            echo "Checking/Creating S3 bucket '${TARGET_BUCKET_NAME}'..."
            mc --config-dir ${MC_CONFIG_DIR} mb temp_minio/${TARGET_BUCKET_NAME} --ignore-existing
            echo "Bucket '${TARGET_BUCKET_NAME}' is present."
            
            # 3. Create the 'pipelines' bucket for KFP artifacts if it doesn't exist.
            echo "Checking/Creating S3 bucket 'pipelines'..."
            mc --config-dir ${MC_CONFIG_DIR} mb temp_minio/pipelines --ignore-existing
            echo "Bucket 'pipelines' is present."

            # 4. Construct the ARN for the server-configured Webhook target and add the event rule.
            TARGET_ARN="arn:minio:sqs::${WEBHOOK_TARGET_ID_IN_MINIO}:webhook"
            echo "Adding/Updating event notification for Webhook target..."
            echo "Target ARN: ${TARGET_ARN}"
            mc --config-dir ${MC_CONFIG_DIR} event add temp_minio/${TARGET_BUCKET_NAME} "${TARGET_ARN}" --event "put" --suffix ".pdf" --ignore-existing

            echo "Event notification rule for Webhook target added/updated."
            
            # 5. Verify and list the configured events.
            echo "Verifying event rules for bucket '${TARGET_BUCKET_NAME}':"
            mc --config-dir ${MC_CONFIG_DIR} event list temp_minio/${TARGET_BUCKET_NAME}
            
            echo "--- MinIO Setup Job Completed Successfully ---"
        env:
          # The internal service host for the MinIO deployment.
          - name: MINIO_SERVICE_HOST
            value: "minio.minio.svc.cluster.local"
          # The internal service port.
          - name: MINIO_SERVICE_PORT
            value: "9000"
          # The name of the bucket where PDFs will be uploaded.
          - name: TARGET_BUCKET_NAME
            value: "pdf-inbox"
          # This ID must match the suffix used for MINIO_NOTIFY_WEBHOOK_* env vars in minio/deployment.yaml
          - name: WEBHOOK_TARGET_ID_IN_MINIO
            value: "RAG"
          # Securely pull credentials from the Kubernetes Secret.
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-root-user
                key: MINIO_ROOT_USER
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-root-user
                key: MINIO_ROOT_PASSWORD
