apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kfp-s3-trigger-allow-all-debug
  namespace: rag-pipeline-workshop
spec:
  selector:
    matchLabels:
      serving.knative.dev/service: kfp-s3-trigger
  rules:
  - {} # This allows ALL authenticated and unauthenticated traffic