apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-minio-to-event-bridge
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: minio-event-bridge
spec:
  selector:
    matchLabels:
      app: minio-event-bridge
  action: ALLOW
  rules:
  - {}  # Empty rule means allow everything
