apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-pipeline-workshop

resources:
- .k8s/kfp-s3-trigger-auth.yaml
- .k8s/vs-ingress.yaml
- .k8s/vs-mesh.yaml
- .k8s/network-policy.yaml
- .k8s/virtual-service.yaml
# Add other resources as they are created

