apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: knative-broker
data:
  # Knative Kafka broker configuration
  bootstrap.servers: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  default.topic.partitions: "10"
  default.topic.replication.factor: "1"

---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
    lastUpdated: yes
  labels:
    app.kubernetes.io/instance: knative-broker
  name: kafka-broker
  namespace: rag-pipeline-workshop
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: rag-pipeline-workshop
  delivery:
    backoffDelay: PT0.2S
    backoffPolicy: exponential
    retry: 10
