apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  high-availability:
    replicas: 1
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      "selector.app": "kourier"
    network:
      "ingress-class": "kourier-internal"
