apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: openshift-serverless
spec:
  ingress:
    kourier:
      enabled: true
  deployments:
  - name: activator
    replicas: 1
  - name: autoscaler
    replicas: 1
  - name: controller
    replicas: 1
  - name: webhook
    replicas: 1
