apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Wave 2: Deploy after core Eventing is ready
spec:
  broker:
    enabled: true
    defaultConfig:
      bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      numPartitions: 10
      replicationFactor: 1
  source:
    enabled: true
  sink:
    enabled: true
  channel:
    enabled: true
    bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
