kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-api-to-eventing-webhook
  namespace: knative-eventing
spec:
  podSelector:
    matchLabels:
      role: eventing-webhook # Or app=eventing-webhook, verify your pod labels
  ingress:
  - ports:
    - protocol: TCP
      port: 8443 # Target port of the webhook pods
    # You might need to add a 'from' clause if your cluster has a restrictive default
    # This example allows from any source, which might be too broad for production.
    # To restrict to API server, you'd need to identify its namespace/pod selectors.