apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: minio-kafka-event-source
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: knative-broker
spec:
  bootstrapServers:
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topics:
    - "minio-bucket-notifications"
  consumerGroup: knative-minio-consumer
  initialOffset: earliest
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
      namespace: rag-pipeline-workshop
