apiVersion: sources.knative.dev/v1beta1 # Using stable v1 API for KafkaSource
kind: KafkaSource
metadata:
  name: minio-kafka-event-source   # A descriptive name for this source
  namespace: rag-pipeline-workshop # CHANGEME: Your serverless application namespace
spec:
  consumerGroup: knative-minio-consumer # As seen working in your logs
  bootstrapServers:
    # Must point to your Kafka cluster's internal listener
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092" # CHANGEME if Kafka details differ
  topics:
    - "minio-bucket-notifications" # The Kafka topic where MinIO sends its events

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker # Sink events to your Kafka-backed broker
      namespace: rag-pipeline-workshop # Explicitly stating namespace

  # KafkaSource wraps the Kafka message payload into a CloudEvent.
  # The default CloudEvent 'type' is often 'dev.knative.kafka.event'.
  # The 'source' attribute will identify this KafkaSource instance.
  # The original MinIO JSON event will be in the 'data' field of the CloudEvent.
  ceOverrides:
    extensions:
      knativekafkasource: "true"
  cloudEventOverrides:
    extensions:
      knativekafkasource: "true"
