apiVersion: sources.knative.dev/v1beta1 # Using the version your cluster serves for KafkaSource
kind: KafkaSource
metadata:
  name: minio-kafka-event-source
  namespace: rag-pipeline-workshop # Your serverless application namespace
spec:
  consumerGroup: knative-minio-consumer # As seen working in your logs
  bootstrapServers:
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092" # Verified Kafka bootstrap service
  topics:
    - "minio-bucket-notifications" # The Kafka topic where MinIO sends its raw JSON events
  # No ceOverrides section - let KafkaSource use its defaults
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker # Your Kafka-backed broker
      namespace: rag-pipeline-workshop