apiVersion: sources.knative.dev/v1beta1 # Or v1 if your cluster supports it and it was working
kind: KafkaSource
metadata:
  name: minio-kafka-event-source
  namespace: rag-pipeline-workshop
spec:
  consumerGroup: knative-minio-consumer
  bootstrapServers:
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topics:
    - "minio-bucket-notifications"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
      namespace: rag-pipeline-workshop
  # ceOverrides: REMOVE THIS SECTION FOR NOW
  #   type: s3:ObjectCreated:Put
  #   extensions:
  #     knativekafkasource: "true"