# services/knative/source.yaml
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: minio-kafka-event-source
  namespace: rag-pipeline-workshop
spec:
  consumerGroup: knative-minio-consumer
  bootstrapServers:
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topics:
    - "minio-bucket-notifications"
  ceOverrides:
    type: "s3:ObjectCreated:Put" # 'type' is a direct child of ceOverrides
    # extensions: # Optional: if you also want to add custom extensions
    #   myCustomExtension: "someValue"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
      namespace: rag-pipeline-workshop