apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger # A descriptive name for this trigger
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: s3-event-handler
spec:
  broker: kafka-broker # Subscribes to your Kafka-backed broker
  filter:
    attributes:
      # This is the typical CloudEvent type emitted by a Knative KafkaSource.
      type: "dev.knative.kafka.event"
      
      # Filter by the specific KafkaSource instance
      source: "/kafkasource/rag-pipeline-workshop/minio-kafka-event-source"
      
      # We're not filtering on specific MinIO event types (like s3:ObjectCreated:Put) here
      # because those are in the data payload that will be processed by the handler
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service # This is a Knative Service
      name: kfp-s3-trigger # The name of your serverless function
      namespace: rag-pipeline-workshop # CHANGEME if different