apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: knative-broker
spec:
  broker: kafka-broker
  filter:
    attributes:
      # Match MinIO's S3 event type
      type: s3:ObjectCreated:Put
      # Optional: can also filter by bucket if needed
      # source: /buckets/pdf-inbox
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kfp-s3-trigger
      namespace: rag-pipeline-workshop
