apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger # Or your actual trigger name
  namespace: rag-pipeline-workshop
spec:
  broker: kafka-broker
  filter:
    attributes:
      # Filter for the default type from KafkaSource
      type: "dev.knative.kafka.event"
      # And specifically from your KafkaSource instance
      source: "/kafkasource/rag-pipeline-workshop/minio-kafka-event-source"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kfp-s3-trigger
      namespace: rag-pipeline-workshop