apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger
  namespace: rag-pipeline-workshop
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: "s3:ObjectCreated:Put" 
      source: "urn:minio:s3:::webhook" # This is what your bridge is now setting as the source
      # You can also add a filter for subject if needed, e.g., for *.pdf
      # subject: ".pdf" # Though this would be a suffix match, Knative filter might need exact or prefix
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: kfp-s3-trigger
        namespace: rag-pipeline-workshop