apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger # Or your preferred trigger name
  namespace: rag-pipeline-workshop
spec:
  broker: kafka-broker
  filter:
    attributes:
      # This should be the default type produced by your KafkaSource v1beta1
      type: "dev.knative.kafka.event"
      # This needs to match the 'source' attribute set by your KafkaSource
      # It's typically /<kind>/<namespace>/<name> but can vary.
      # You MUST verify this by inspecting an actual event on the broker topic.
      source: "/kafkasource/rag-pipeline-workshop/minio-kafka-event-source"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kfp-s3-trigger
      namespace: rag-pipeline-workshop