apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger # Or your preferred trigger name
  namespace: rag-pipeline-workshop
  annotations:
    kafka.eventing.knative.dev/delivery.enable.debug: "true"  # Enable debug logging
spec:
  broker: kafka-broker # Subscribes to your Kafka-backed broker
  filter:
    attributes:
      "$data":
        Records:
          - eventSource: minio:s3
            eventName: s3:ObjectCreated:Put
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kfp-s3-trigger # Your Knative Service
      namespace: rag-pipeline-workshop
