apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger # A descriptive name for this trigger
  namespace: rag-pipeline-workshop
  labels:
    app.kubernetes.io/instance: s3-event-handler
spec:
  broker: kafka-broker # Subscribes to your Kafka-backed broker
  filter:
    attributes:
      type: dev.knative.kafka.event
      source: /kafkasource/rag-pipeline-workshop/minio-kafka-event-source
      # The actual MinIO event data will be in the CloudEvent's data field
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service # This is a Knative Service
      name: kfp-s3-trigger # The name of your serverless function
      namespace: rag-pipeline-workshop # CHANGEME if different