apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: minio-pdf-event-trigger
  namespace: rag-pipeline-workshop
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: "dev.knative.kafka.event"
      source: "/kafkasource/rag-pipeline-workshop/minio-kafka-event-source"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kfp-s3-trigger
      namespace: rag-pipeline-workshop
