apiVersion: v1
kind: ConfigMap
metadata:
  name: vectordb-milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
data:
  # user.yaml is kept minimal, allowing most settings to come from the default.
  user.yaml: |
    etcd:
      endpoints:
        - vectordb-etcd:2379 # Points to the etcd service within the same namespace
    minio:
      address: localhost:9000
    common:
      # Use internal component names for standalone mode with separate etcd
      rootCoord:
        address: localhost:53100
      dataCoord:
        address: localhost:13333
      queryCoord:
        address: localhost:19531
      indexCoord:
        address: localhost:31000
  # default.yaml can be left empty as the container image contains the defaults.
  # The run-helm.sh script will merge user.yaml over the internal defaults.
  default.yaml: |
    {}