apiVersion: v1
kind: ConfigMap
metadata:
  name: vectordb-milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
data:
  user.yaml: |
    # This configuration is the intended setup, but we will override etcd.endpoints
    # via an environment variable to ensure it's applied correctly.
    etcd:
      endpoints:
        - vectordb-etcd-headless:2379 
    
    minio:
      address: localhost:9000
    common:
      rootCoord:
        address: localhost:53100
      dataCoord:
        address: localhost:13333
      queryCoord:
        address: localhost:19531
      indexCoord:
        address: localhost:31000
  default.yaml: |
    {} # The container image includes default configurations.