apiVersion: v1
kind: ConfigMap
metadata:
  name: vectordb-milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
data:
  user.yaml: |
    # THIS IS THE CRITICAL FIX:
    # This configuration points Milvus to the external etcd StatefulSet's service endpoint,
    # not localhost. This resolves the "connection refused" error.
    etcd:
      endpoints:
        - vectordb-etcd-headless:2379 
    
    # The following components run inside the standalone pod and communicate via localhost.
    minio:
      address: localhost:9000
    common:
      rootCoord:
        address: localhost:53100
      dataCoord:
        address: localhost:13333
      queryCoord:
        address: localhost:19531
      indexCoord:
        address: localhost:31000
  default.yaml: |
    {} # The container image includes default configurations.