apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Sufficient forthis small workshop-scale data.