apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectordb-milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi