apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  annotations:
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: milvus
spec:
  type: ClusterIP # Only exposes the service inside the cluster.
  ports:
  - name: grpc
    port: 19530
    targetPort: milvus-grpc
    protocol: TCP
  - name: http
    port: 9091
    targetPort: milvus-http
    protocol: TCP
  selector:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: milvus

---

# 2. Headless Service for the etcd StatefulSet
# Provides a stable network identity for the etcd pod(s).
apiVersion: v1
kind: Service
metadata:
  name: vectordb-etcd-headless
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
  annotations:
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
  - name: peer
    port: 2380
    protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb