apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster       # Name of your Kafka cluster
  namespace: kafka # CHANGEME: Namespace for Kafka deployment
spec:
  kafka:
    version: 3.6.0            # Specify a Kafka version supported by your AMQ Streams Operator
    replicas: 1               # Single broker for PoC. Increase for HA.
    listeners:
      # Plain listener on 9092 for internal cluster communication
      - name: plain
        port: 9092
        type: internal
        tls: false
      # TLS listener on 9093 (optional, but good practice for clients if needed)
      # - name: tls
      #   port: 9093
      #   type: internal
      #   tls: true
    storage:
      type: ephemeral         # WARNING: Ephemeral storage. Data lost on pod deletion.
                              # For production, use 'persistent-claim' and configure 'size'.
                              # Example for persistent storage:
                              # type: persistent-claim
                              # size: 100Gi
                              # deleteClaim: false # Set to true if you want PVC deleted when Kafka cluster is deleted
    config:                   # Basic Kafka broker configurations
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.6" # Match your Kafka version
      inter.broker.protocol.version: "3.6" # Match your Kafka version
    resources:                # Adjust based on your cluster capacity
      requests:
        memory: 512Mi
        cpu: "250m"
      limits:
        memory: 1Gi
        cpu: "500m"
  zookeeper:
    replicas: 1               # Single Zookeeper node for PoC.
    storage:
      type: ephemeral         # WARNING: Ephemeral storage.
                              # Example for persistent storage:
                              # type: persistent-claim
                              # size: 20Gi
                              # deleteClaim: false
    resources:                # Adjust based on your cluster capacity
      requests:
        memory: 256Mi
        cpu: "100m"
      limits:
        memory: 512Mi
        cpu: "250m"
  entityOperator:             # Manages KafkaTopics and KafkaUsers
    topicOperator: {}         # Enable Topic Operator (to manage KafkaTopic CRs)
    userOperator: {}          # Enable User Operator (if you plan to use KafkaUser CRs for ACLs)