apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: minio-bucket-notifications # Name of your Kafka topic
  namespace: kafka                  # CHANGEME: Must be the SAME namespace as your Kafka cluster CR
  labels:
    # This label links the topic to the specific Kafka cluster managed by Strimzi
    strimzi.io/cluster: kafka-cluster # MUST match metadata.name in your Kafka CR (kafka-cluster.yaml)
spec:
  partitions: 3     # Number of partitions for the topic (e.g., 3 is a common starting point)
  replicas: 1       # Replication factor for the topic messages.
                    # For a single-broker Kafka cluster (as in the example above), this MUST be 1.
                    # For a multi-broker Kafka cluster, set <= number of brokers (e.g., 3 for 3 brokers).
  config:
    retention.ms: 604800000 # Example: 7 days message retention (optional)
    # segment.bytes: 1073741824 # Example: 1 GB segment size (optional)